import type { GherkinKeyword, GherkinSection } from './base';

type GherkinExamples = {
  headers: string[];
  rows: string[][];
};

type CaseType = {
  id: number;
  title: string;
  state: number;
  priority: number;
  type: number;
  automationStatus: number;
  description: string;
  template: number;
  preConditions: string;
  expectedResults: string;
  folderId: number;
  gherkinExamples?: GherkinExamples | null;
  Steps?: StepType[];
  RunCases?: RunCaseType[];
  Attachments?: AttachmentType[];
  Tags?: {
    id: number;
    name: string;
  }[];
};

type CaseStepType = {
  createdAt?: Date;
  updatedAt?: Date;
  CaseId?: number;
  StepId?: number;
  stepNo: number;
  keyword?: GherkinKeyword | null;
  section?: GherkinSection | null;
};

type StepType = {
  id: number;
  step: string;
  result: string;
  createdAt: Date;
  updatedAt: Date;
  caseSteps: CaseStepType;
  uid: string;
  editState: 'notChanged' | 'changed' | 'new' | 'deleted';
};

type RunCaseType = {
  id: number;
  runId: number;
  caseId: number;
  status: number;
  editState: 'notChanged' | 'changed' | 'new' | 'deleted';
  commentCount?: number;
  assigneeUserId: number | null;
};

type CaseAttachmentType = {
  createdAt: Date;
  updatedAt: Date;
  caseId: number;
  attachmentId: number;
};

type AttachmentType = {
  id: number;
  title: string;
  detail: string;
  filename: string;
  createdAt: Date;
  updatedAt: Date;
  caseAttachments: CaseAttachmentType;
};

type CasesMessages = {
  testCaseList: string;
  id: string;
  title: string;
  priority: string;
  actions: string;
  deleteCase: string;
  close: string;
  areYouSure: string;
  delete: string;
  newTestCase: string;
  export: string;
  status: string;
  noCasesFound: string;
  caseTitle: string;
  caseDescription: string;
  caseTitleOrDescription: string;
  create: string;
  pleaseEnter: string;
  filter: string;
  clearAll: string;
  apply: string;
  selectPriorities: string;
  selected: string;
  type: string;
  selectTypes: string;
  casesSelected: string;
  selectAction: string;
  move: string;
  clone: string;
  casesMoved: string;
  tags: string;
  casesCloned: string;
  selectTags: string;
  import: string;
  importCases: string;
  importAvailable: string;
  downloadTemplate: string;
  clickToUpload: string;
  orDragAndDrop: string;
  maxFileSize: string;
  casesImported: string;
  createMore: string;
  successTitle: string;
  errorTitle: string;
  errorFetchingTags: string;
  priorityFilter: string;
  typeFilter: string;
  tagFilter: string;
  testCaseActions: string;
  exportOptions: string;
  noTestCase: string;
  template: string;
  text: string;
  step: string;
  gherkin: string;
};

type CaseMessages = {
  backToCases: string;
  loading: string;
  requestError: string;
  retry: string;
  retryAfter: string;
  correlationId: string;
  updating: string;
  update: string;
  updatedTestCase: string;
  basic: string;
  title: string;
  pleaseEnterTitle: string;
  description: string;
  testCaseDescription: string;
  priority: string;
  type: string;
  template: string;
  testDetail: string;
  preconditions: string;
  expectedResult: string;
  step: string;
  text: string;
  steps: string;
  newStep: string;
  detailsOfTheStep: string;
  deleteThisStep: string;
  insertStep: string;
  attachments: string;
  delete: string;
  download: string;
  deleteFile: string;
  clickToUpload: string;
  orDragAndDrop: string;
  maxFileSize: string;
  areYouSureLeave: string;
  tags: string;
  createTag: string;
  maxTagsLimit: string;
  tagAlreadyExists: string;
  tagCreatedAndAdded: string;
  errorCreatingTag: string;
  errorUpdatingTestCase: string;
  searchOrCreateTag: string;
  noTagsSelected: string;
  successTitle: string;
  errorTitle: string;
  warningTitle: string;
  errorFetchingTags: string;
  gherkin: string;
  given: string;
  when: string;
  then: string;
  and: string;
  but: string;
  background: string;
  scenario: string;
  examples: string;
  addExamples: string;
  removeExamples: string;
  addExampleRow: string;
  removeExampleRow: string;
  addExampleColumn: string;
  removeExampleColumn: string;
  exampleHeader: string;
  exampleValue: string;
  noExamples: string;
  noScenarioSteps: string;
  gherkinValidationStepsRequired: string;
  gherkinValidationStepOrder: string;
  gherkinValidationKeyword: string;
  gherkinValidationSection: string;
  gherkinValidationStepText: string;
  gherkinValidationDuplicateStep: string;
  gherkinValidationFirstConnector: string;
  gherkinValidationRequiredKeywords: string;
  gherkinValidationExamples: string;
  gherkinValidationPlaceholder: string;
  gherkinValidationDetailsKeyword: string;
};

export type { CaseType, CaseStepType, StepType, AttachmentType, CasesMessages, CaseMessages, GherkinExamples };
